#include QMK_KEYBOARD_H

#include "print.h"


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes {
    WJM_SUPERCALC = SAFE_RANGE,
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  /* (Base Layer) Default Layer
   * |---------------------------------------------------------------------------------------------------------------------------------|
   * | Esc |  F1  |  F2  |  F3  |  F4  |      F5  |  F6  |  F7  |  F8  |      F9  |  F10 |  F11 |  F12 |   Delete   |    Prtsc    |
   * |---------------------------------------------------------------------------------------------------------------------------------|
   * |  ~  |     1   |   2   |   3   |   4   |    5      |       6    |    7    |    8   |   9  |   0  |   [  |  ]  |  Backspace  |
   * |---------------------------------------------------------------------------------------------------------------------------------|
   * | Tab |   '    |    ,   |   .  |   p  |   Y  |            |    F   |    G   |    C  |   R  |   L  |   /  |  =  |   \  | Home |
   * |---------------------------------------------------------------------------------------------------------------------------------|
   * | Ctl |   A   |   O   |   E  |   U  |   I  |      Bksp      |    D  |    H   |   T  |   N  |   S  |  -   |    Enter   | End  |
   * |---------------------------------------------------------------------------------------------------------------------------------|
   * |Shift|   ;  |   Q  |   J  |   K  |   X  |       Enter       |    B  |    M   |  W  |   V  |   Z  | Shift|      |  Up |
   * |---------------------------------------------------------------------------------------------------------------------------------|
   * |Ctrl | GUI |     Alt     |    Space   |   Ctrl   |   Shift   |     Space     |    Alt     |  FN  | Ctrl | Lft  |  Dn |  Rig |
   * |---------------------------------------------------------------------------------------------------------------------------------|
   */
  [0] = LAYOUT(
    KC_ESC,  KC_F1,   KC_F2,   KC_F3,      KC_F4,   KC_F5,   KC_F6,      KC_F7,   KC_F8,   KC_F9,         KC_F10,  KC_F11,  KC_F12,       KC_DEL,  KC_PSCR,
    KC_GRV,  KC_1,    KC_2,    KC_3,       KC_4,    KC_5,    KC_6,       KC_7,    KC_8,    KC_9,          KC_0,    KC_LBRC, KC_RBRC,      KC_BSPC,
    KC_TAB,  KC_QUOT, KC_COMM, KC_DOT,     KC_P,    KC_Y,    KC_F,       KC_G,    KC_C,    KC_R,          KC_L,    KC_SLSH, KC_EQL,       KC_BSLS, KC_HOME,
    KC_LSFT, KC_A,    KC_O,    KC_E,       KC_U,    KC_I,    KC_ESC,     KC_D,    KC_H,    KC_T,          KC_N,    KC_S,    KC_MINS,      KC_ENT,  KC_END,
    KC_LCTL, KC_SCLN, KC_Q,    KC_J,       KC_K,    KC_X,    KC_ENT,     KC_B,    KC_M,    KC_W,          KC_V,    KC_Z,    KC_RSFT,      KC_UP,
    KC_CAPS, KC_LGUI, KC_LALT, KC_SPC,     KC_LCTL, KC_LSFT, KC_SPC,     KC_RALT, MO(1),   KC_RCTL,       KC_LEFT, KC_DOWN, KC_RGHT
    ),

  [1] = LAYOUT(
    QK_BOOT, DB_TOGG, _______, _______,    _______, _______, _______,    _______, _______, WJM_SUPERCALC, KC_MYCM, KC_MSEL, KC_MAIL,      NK_TOGG, EE_CLR,
    _______, _______, _______, _______,    _______, _______, _______,    _______, _______, _______,       _______, _______, LCTL(KC_BRK), TG(2),
    RGB_TOG, RGB_MOD, RGB_VAI, RGB_HUI,    _______, _______, _______,    _______, _______, _______,       _______, _______, _______,      _______, KC_PGUP,
    _______, RGB_SPD, RGB_VAD, RGB_SPI,    _______, _______, _______,    _______, _______, _______,       _______, _______, _______,      _______, KC_PGDN,
    _______, _______, _______, _______,    _______, _______, _______,    _______, _______, LALT(KC_PAST), _______, _______, KC_MUTE,      KC_VOLU,
    _______, _______, _______, KC_MS_BTN1, _______, _______, KC_MS_BTN2, _______, _______, KC_MPLY,       KC_MPRV, KC_VOLD, KC_MNXT
    ),

  [2] = LAYOUT(
    _______, _______, _______, _______,    _______, _______, _______,    _______, _______, _______,       _______, _______, _______,      _______, _______,
    _______, _______, _______, _______,    _______, _______, _______,    KC_P7,   KC_P8,   KC_P9,         KC_PMNS, _______, _______,      _______,
    _______, _______, _______, _______,    _______, _______, _______,    KC_P4,   KC_P5,   KC_P6,         KC_PPLS, _______, _______,      _______, _______,
    _______, _______, _______, _______,    _______, _______, _______,    _______, KC_P1,   KC_P2,         KC_P3,   KC_PEQL, _______,      _______, _______,
    _______, _______, _______, _______,    _______, _______, _______,    _______, KC_P0,   _______,       KC_PDOT, _______, _______,      _______,
    _______, _______, _______, _______,    _______, _______, _______,    _______, _______, _______,       _______, _______, _______
    ),
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

void keyboard_post_init_user(void) {
    //debug_enable = true;
}

bool process_record_user( uint16_t keycode, keyrecord_t *record ) {
    if( record->event.pressed ) {
        switch( keycode ) {
            case WJM_SUPERCALC:
                SEND_STRING(SS_TAP(X_CALC));
                layer_on(2);
                return false;
        }
    }
    return true;
}


