
OLED_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = yes

DYNAMIC_TAPPING_TERM_ENABLE = yes
CAPS_WORD_ENABLE = yes
SEND_STRING_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMMAND_ENABLE = no
KEY_OVERRIDE_ENABLE = yes

CONVERT_TO = promicro_rp2040
