
OLED_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes

DYNAMIC_TAPPING_TERM = yes
CAPS_WORD_ENABLE = yes
SEND_STRING_ENABLE = yes
MOUSE_KEY_ENABLE = yes
COMMAND_ENABLE = no
